# -*- coding: utf-8 -*-
"""Zillow Scraper New.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qtKz51WwM0Wu9jAYvqe6XeAeFz0EOZHj
"""

from bs4 import BeautifulSoup                           # pip install bs4
import requests                                         # pip install requests
import re
import time
import pandas as pd                                     # pip install pandas
import string

zips = [22030,23452,23454,22407,22192,23320,22554,24060,22204,23456,23112,20176,23223,23666,20148,20171,23434,23455,22304,23185,20110,24502,23234,22015,23188,23451,20109,23608,23225,20170,20164,22801,20120]

u1 = 'https://www.zillow.com/'

u2 = 'jefferson-county-al' #county_name_with_state

u3 = '/sold/'

u4 = 'land_type/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%22'
u44= 'land_type/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22'
u5 = 'filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22days%22%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22rs%22%3A%7B%22value%22%3Atrue%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%2C%22sf%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22mf%22%3A%7B%22value%22%3Afalse%7D%2C%22manu%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D'
u55= 'regionSelection%22%3A%5B%7B%22regionId%22%3A2732%2C%22regionType%22%3A4%7D%5D%2C%22isMapVisible%22%3Atrue%2C%22filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22globalrelevanceex%22%7D%2C%22rs%22%3A%7B%22value%22%3Atrue%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22sf%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%2C%22mf%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22manu%22%3A%7B%22value%22%3Afalse%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D'
u6 = 'filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22globalrelevanceex%22%7D%2C%22rs%22%3A%7B%22value%22%3Atrue%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D'
url = u1+u2+u3+u44+u55

print(url)

def app(z):
    qq = 'https://www.zillow.com/homes/'
    ss = z
    tt = '_rb/'
    u = qq+ss+tt
    
    d = u

    aa = d+'sold/'

    bb = 'land_type/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%2227591%22%2C%22'

    cc = 'filterState%22%3A%7B%22doz%22%3A%7B%22value%22%3A%2212m%22%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%2C%22sort%22%3A%7B%22value%22%3A%22globalrelevanceex%22%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22rs%22%3A%7B%22value%22%3Atrue%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22sf%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%2C%22mf%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22manu%22%3A%7B%22value%22%3Afalse%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%2C%22price%22%3A%7B%22min%22%3A90000%2C%22max%22%3A125000%7D%2C%22mp%22%3A%7B%22min%22%3A389%2C%22max%22%3A540%7D%2C%22lot%22%3A%7B%22min%22%3A87120%2C%22max%22%3A871200%7D%7D%2C%22isListVisible%22%3Atrue%7D'

    u1 = 'https://www.zillow.com/'

    u2 = county_name_with_state

    u3 = '/sold/'

    u4 = 'land_type/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%22'

    u5 = 'filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22days%22%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22rs%22%3A%7B%22value%22%3Atrue%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%2C%22sf%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22mf%22%3A%7B%22value%22%3Afalse%7D%2C%22manu%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D'

https://www.zillow.com/jefferson-county-al/sold/land_type/?searchQueryState=%7B%22pagination%22%3A%7B%7D%2C%22usersSearchTerm%22%3A%22Jefferson%20County%2C%20AL%22%2C%22mapBounds%22%3A%7B%22west%22%3A-87.55059418457031%2C%22east%22%3A-86.30776581542969%2C%22south%22%3A33.22176126140927%2C%22north%22%3A33.86729710902507%7D%2C%22
regionSelection%22%3A%5B%7B%22regionId%22%3A2732%2C%22regionType%22%3A4%7D%5D%2C%22isMapVisible%22%3Atrue%2C%22
filterState%22%3A%7B%22sort%22%3A%7B%22value%22%3A%22days%22%7D%2C%22fsba%22%3A%7B%22value%22%3Afalse%7D%2C%22fsbo%22%3A%7B%22value%22%3Afalse%7D%2C%22nc%22%3A%7B%22value%22%3Afalse%7D%2C%22fore%22%3A%7B%22value%22%3Afalse%7D%2C%22cmsn%22%3A%7B%22value%22%3Afalse%7D%2C%22auc%22%3A%7B%22value%22%3Afalse%7D%2C%22rs%22%3A%7B%22value%22%3Atrue%7D%2C%22ah%22%3A%7B%22value%22%3Atrue%7D%2C%22sf%22%3A%7B%22value%22%3Afalse%7D%2C%22con%22%3A%7B%22value%22%3Afalse%7D%2C%22mf%22%3A%7B%22value%22%3Afalse%7D%2C%22manu%22%3A%7B%22value%22%3Afalse%7D%2C%22tow%22%3A%7B%22value%22%3Afalse%7D%2C%22apa%22%3A%7B%22value%22%3Afalse%7D%2C%22apco%22%3A%7B%22value%22%3Afalse%7D%7D%2C%22isListVisible%22%3Atrue%2C%22mapZoom%22%3A11%7D
    url = aa+bb+cc
    return url

def scrap(url):
  PAUSE_SECONDS = 10   
  req_headers = {
      'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-US,en;q=0.8',
      'upgrade-insecure-requests': '1',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'
  }

  req_proxy = {'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
              'accept-encoding': 'gzip, deflate, sdch, br',
              'accept-language': 'en-GB,en;q=0.8,en-US;q=0.6,ml;q=0.4',
              'cache-control': 'max-age=0',
              'upgrade-insecure-requests': '1',
              'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36'}

  time.sleep(PAUSE_SECONDS)
  with requests.Session() as s:
    proxy = req_proxy
    response = s.get(url, headers=req_headers)
  try:
    soup = BeautifulSoup(response.text, 'html.parser')
    sold = soup.find('span', class_="result-count").text
  except:
    sold = '0'
  return sold

solds=[]
g = 0
for i in range(len(zips)):
  zip = str(zips[i])
  api = app(zip)
  #print(api)

  g = g+1

  if g%5==0:
    time.sleep(60)
    sold = scrap(api)
  else:
    time.sleep(10)
    sold = scrap(api)

  print(f'Found {sold} for {zips[i]}')
  data = [zips[i],sold,api]
  solds.append(data)
  time.sleep(4)

  gf = pd.DataFrame (solds, columns = ['Zip Code','Sold Amount','Link'])
  gf['Sold Amount'] = gf['Sold Amount'].str.replace(r' results', '')
  gf['Sold Amount'] = pd.to_numeric(gf['Sold Amount'])

try:
  h =0
  filter = gf['Sold Amount'] < 1
  pf = gf[filter]
  pf.reset_index(inplace=True)
  solds2=[]
  for k in range(len(pf['Zip Code'])):
    zip2 = str(pf['Zip Code'][k])
    api2 = app(zip2)
    #print(api2)

    h = h+1

    if h%5==0:
      time.sleep(60)
      sold2 = scrap(api2)
    else:
      sold2 = scrap(api2)

    print(f'Trying Again for {zip2} Found {sold2} ')
    data2 = [zip2,sold2,api2]
    solds2.append(data2)
    time.sleep(4)

  gf2 = pd.DataFrame (solds2, columns = ['Zip Code','Sold Amount','Link'])
  gf2['Sold Amount'] = gf2['Sold Amount'].str.replace(r' results', '')
  gf2['Sold Amount'] = pd.to_numeric(gf2['Sold Amount'])

  gf.drop(gf.index[gf['Sold Amount'] == 0], inplace=True)

  new_gf = pd.concat([gf, gf2])
  new_gf.to_csv('Zillow Sold Comps.csv')
  print(new_gf)

except:
  gf.to_csv('Zillow Sold Comps.csv')
  print(gf)

